### ISSUE TITLE
Релиз нового альбома

### ISSUE THREAD

**Issue by fruktoviy** [followthecompass/web#1]
Альбом уже в предзаказе. 12 октября будет полностью доступен на всех сторах. То есть все ссылки (на spotify, googleplay, youtube , amazon) будут ровно 12 октября! И надо будет их оперативно добавить в этот день. Сейчас можно уже добавить ссылки ниже.
Также обновить главную страницу нужно - добавить и туда кавер альбома (как сейчас сделан сингл на главной)

Альбом Colors -
ссылки на предзаказ:

Bandcamp -
https://followthecompass.bandcamp.com/album/colors
Apple - 
https://music.apple.com/ru/album/colors/1480759320

Ссылка на обложки : https://disk.yandex.ru/client/disk/FTC%20Covers
(Follow The Compass - 2019 - Colors.1 или Follow The Compass - 2019 - Colors.2)

**Comment by TorinAsakura** [comment]
@fruktoviy расшарь потом папочку для пользователя me@followthecompass.ru чтобы данные всегда доступны были

**Comment by TorinAsakura** [comment]
@fruktoviy ссылка не рабочая кстати

**Comment by fruktoviy** [comment]
https://yadi.sk/d/nOWsg0C_OGX8jA

**Comment by TorinAsakura** [comment]
@fruktoviy https://followthecompass.ru/relizy/colors/

**Comment by TorinAsakura** [comment]
@fruktoviy хреново, что тайтл альбома в левом-верхнем углу( Не подпадает под паттерн для слайдера(
![Снимок экрана 2019-10-09 в 22 00 50](https://user-images.githubusercontent.com/3940885/66511868-73547700-eae0-11e9-8fe1-9985c9193f52.png)

**Comment by fruktoviy** [comment]
@TorinAsakura да вроде бы все ок, зато не дублируется

**Comment by fruktoviy** [comment]
Нужно добавить на сайт еще ссылки на релиз:


Spotify - https://open.spotify.com/artist/39vK00NwYHqu9INLkgBC4F?si=DgcG5QmxRZeu60e7jdB2gQ
YouTube Music - https://music.youtube.com/playlist?list=OLAK5uy_k5nv0mZmCFexhOUmfv6d_gqXwFSPFzmAo
Amazon - https://www.amazon.com/Colors-Follow-Compass/dp/B07Y5CW5F5/ref=sr_1_1?keywords=Follow+The+Compass&qid=1570887456&s=dmusic&search-type=ss&sr=1-1

**Comment by TorinAsakura** [comment]
@fruktoviy а остальные ссылки где?

**Comment by fruktoviy** [comment]
ошибка
 
![Снимок](https://user-images.githubusercontent.com/55533678/66719625-326ba380-edfb-11e9-8ac3-84176587acb6.JPG)
![Снимок1](https://user-images.githubusercontent.com/55533678/66719626-33043a00-edfb-11e9-809f-8c0d6036b150.JPG)

когда нажимаешь на ссылку на эпл

**Comment by fruktoviy** [comment]
я не понимаю, причем тут сайт для сокращения ссылок в адресной строке? 
ссылки же прямые на релиз -
https://music.apple.com/ru/album/colors/1480759320

**Comment by TorinAsakura** [comment]
Используется яблочный сервис apple toolbox, видимо с ним что-то не так--Отправлено из мобильной Яндекс.Почты13.10.2019, 20:57, "fruktoviy" <notifications@github.com>:я не понимаю, причем тут сайт для сокращения ссылок в адресной строке?
ссылки же прямые на релиз -
https://music.apple.com/ru/album/colors/1480759320

**Comment by fruktoviy** [comment]
![Снимок](https://user-images.githubusercontent.com/55533678/66719747-685d5780-edfc-11e9-9d7c-24779b4380d5.JPG)

**Comment by TorinAsakura** [comment]
Завтра буду разбираться --Отправлено из мобильной Яндекс.Почты13.10.2019, 21:00, "fruktoviy" <notifications@github.com>:

**Comment by TorinAsakura** [comment]
Всё готово
