### ISSUE TITLE
добавить в раздел "о проекте"

### ISSUE THREAD

**Issue by fruktoviy** [followthecompass/web#4]
нужно добавить новый абзац  перед строкой:
"На данный момент музыканты готовят обновленную программу для выступлений."

В октябре 2019 года был презентован новый альбом Colors. На данный момент это, пожалуй, самый взрослый релиз проекта. Обложка альбома раскрывает его философию: внутри каждого из нас живёт уникальный набор красок, а также оттенки, которые вы в себе еще не открыли, но они существуют. Этой палитрой настроений мы рисуем мир вокруг нас.

**Comment by fruktoviy** [comment]
то есть вот сюда вместо желтого маркера: 
![Снимок](https://user-images.githubusercontent.com/55533678/68595505-99d44c00-04aa-11ea-8235-1f85c1f7bafe.JPG)

**Comment by fruktoviy** [comment]
"и материал для нового альбома." удалить.
чтобы получилось последним предложением

"На данный момент музыканты готовят обновленную программу для выступлений."

**Comment by TorinAsakura** [comment]
> "и материал для нового альбома." удалить.
> чтобы получилось последним предложением
> 
> "На данный момент музыканты готовят обновленную программу для выступлений."

Так. Прекрати это. Напиши полностью сюда текст который нужно поместить на сайт и прекрати швыряться такими кусками

**Comment by fruktoviy** [comment]
Follow The Compass – музыкальный проект из Санкт-Петербурга, созданный бас-гитаристом Александром Мухиным 22 апреля 2012 года. Эта дата является одновременно и датой выхода альбома First Flight. Альбом содержит 8 композиций, полностью сыгранных на бас-гитаре. Это был первый опыт работы музыканта в качестве сольного исполнителя.

В том же 2012 году к четырехструнному инструменту Саши присоединились клавиши (Дарья Пчелинцева), и уже в июле вышел EP Looking Forward. В конце года дуэт дал первые два концерта: в Москве и Санкт-Петербурге.

В январе 2014 года Дарью в коллективе заменила пианистка Ксения Пономарева. Сразу найдя точки соприкосновения, ребята сели за запись второго альбома Imagination, который вышел уже в июле того же года. В новом альбоме появилось больше новых красок и инструментов. Немаловажную роль в этом сыграло полное взаимопонимание между музыкантами и профессиональный опыт Ксюши в качестве звукорежиссера. В конце 2014, начале 2015 года дуэт дал два концерта в Санкт-Петербурге и Москве в поддержку альбома Imagination.

В 2015 году музыканты сели за запись мини-альбома, который впоследствии было решено сделать полноценным: так в апреле 2016 года вышел альбом под названием Inside. Новый альбом стал более медитативным и экспериментальным. Его обложка, показывающая калейдоскоп изнутри, призвана настроить слушателя на более глубокое познание себя.

Концерты в поддержку альбома музыканты решили дополнить еще одним инструментом – виолончелью. Так в составе коллектива появилась Валерия Стемасова, которая в конце 2016 года отыграла с группой в ставших традиционными для выступлений российских столицах. Лера гармонично дополнила старые композиции и украсила звучание новых работ. В 2017 году музыканты официально объявили, что теперь их команда состоит из трех участников.

В октябре 2019 года был презентован новый альбом Colors. На данный момент это, пожалуй, самый взрослый релиз проекта. Обложка альбома раскрывает его философию: внутри каждого из нас живёт уникальный набор красок, а также оттенки, которые вы в себе еще не открыли, но они существуют. Этой палитрой настроений мы рисуем мир вокруг нас.

На данный момент музыканты готовят обновленную программу для выступлений.

**Comment by fruktoviy** [comment]
ну как, скоро сможешь обновить раздел?

**Comment by TorinAsakura** [comment]
>ну как, скоро сможешь обновить раздел? ...

@fruktoviy от того, что ты будешь постоянно об этом напоминать и спамить в тикеты - быстрее ничего не сделается

**Comment by TorinAsakura** [comment]
@fruktoviy https://followthecompass.ru/o-proekte/

**Comment by fruktoviy** [comment]
Класс!
