### ISSUE TITLE
Добавить на сайт новое видео

### ISSUE THREAD

**Issue by fruktoviy** [followthecompass/web#5]
добавить на сайт в раздел видео 
ссылка - https://www.youtube.com/watch?v=njR_V6sIPRM&feature=emb_logo
(Follow The Compass - Colors (Full Album, 2019))

на главной странице не нужно обновлять видео, пусть остается, как есть сейчас

**Comment by TorinAsakura** [comment]
@fruktoviy положи пожалуйста постер к видео, в высоком качестве разумеется в нашу папку в Yandex. Disk

**Comment by fruktoviy** [comment]
её не существует. постером является скрин из видео. хорошего качества там точно не будет. 
в качестве альтернативы могу предложить просто фото обложки, как "постер к видео" или же оставить так как есть. так как это не сильно критично, на мой взгляд.. видео не должно быть на главной странице сайта (там видео Colors с парусниками), а просто в разделе "видео".

**Comment by TorinAsakura** [comment]
@fruktoviy https://followthecompass.ru/video/
